spring.main.banner-mode=off
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://busjourney-prod-kv-2.vault.azure.net/
spring.cloud.azure.keyvault.secret.property-source-enabled=true

# This enables the default Azure credential chain (Managed Identity -> CLI -> Environment)
spring.cloud.azure.keyvault.secret.credential.managed-identity-enabled=true

# Correct property name for 5.x
spring.cloud.azure.keyvault.secret.property-sources[0].refresh-interval=3600s

# MySQL Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/busjourney_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.url=${mysql-connection-string:jdbc:mysql://localhost:3306/busjourney_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${mysql-username:root}
spring.datasource.password=${mysql-password:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


